CC = clang
CFLAGS = -Weverything -Werror -std=c2x -O3 -Wno-poison-system-directories -Wno-padded
CXX = clang++
CXXFLAGS = -Weverything -Werror -std=c++20 -Wno-poison-system-directories -Wno-c++98-compat

all: check exhaustive large midpoint types

clean:
	@rm check exhaustive large midpoint types
